import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Route, Routes, useLocation } from 'react-router-dom'
import InteractiveServicesPage from './ServicesPage'
import './index.css'
import './overrides.css'
import './light-overrides.css'

type Lang = 'TJ' | 'RU' | 'EN'
const languages: Lang[] = ['TJ', 'RU', 'EN']

function Layout({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('TJ')
  const [menu, setMenu] = useState(false)
  const location = useLocation()
  useEffect(() => { document.documentElement.dataset.theme = 'light' }, [])
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' as ScrollBehavior }); setMenu(false) }, [location.pathname])
  const nextLang = () => setLang(languages[(languages.indexOf(lang) + 1) % languages.length])
  return <div className="app-shell"><header className="topbar"><div className="nav-wrap"><Link to="/" className="brand"><span className="brand-mark">✦</span><span><b>ePanjakent</b><small>DIGITAL CITY</small></span></Link><nav className="desktop-nav"><Link to="/news">Хабарҳо</Link><Link to="/history">Таърих ва фарҳанг</Link><Link to="/tourism">Туризм</Link><Link to="/services">Хизматҳо</Link><Link to="/digital">Рақамӣ</Link><Link to="/appeals">Муроҷиатҳо</Link></nav><div className="nav-actions"><button onClick={nextLang} aria-label="Change language">🌐 <strong>{lang}</strong></button><button className="menu-btn" onClick={() => setMenu(!menu)} aria-label="Open menu">{menu ? '×' : '☰'}</button></div></div>{menu && <div className="mobile-menu"><Link to="/news">Хабарҳо</Link><Link to="/history">Таърих ва фарҳанг</Link><Link to="/tourism">Туризм</Link><Link to="/services">Хизматҳо</Link><Link to="/digital">Рақамӣ</Link><Link to="/appeals">Муроҷиатҳо</Link></div>}</header><main>{children}</main><footer><div className="footer-inner"><Link to="/" className="brand"><span className="brand-mark">✦</span><span><b>ePanjakent</b><small>DIGITAL CITY PORTAL</small></span></Link><p>© 2026 ePanjakent · Panjakent, Tajikistan</p><div>🇹🇯 🇷🇺 🇬🇧</div></div></footer></div>
}
const news=[{tag:'ХАБАРҲО',title:'Панҷакент: марҳилаи нави рушди шаҳри рақамӣ',text:'Хизматрасониҳои муосир ва ташаббусҳои нави рақамӣ барои сокинон.',image:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=85'},{tag:'ФАРҲАНГ',title:'Мероси бостонии Панҷакент зинда аст',text:'Гузаштаи пурғановати шаҳр қисми муҳими ояндаи он мебошад.',image:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85'},{tag:'ЧОРАБИНӢ',title:'Роҳнамои нави сайёҳӣ ба меҳмонон пешниҳод шуд',text:'Масирҳои нав ба Панҷакенти қадим, Саразм ва Ҳафт Кӯл.',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85'}]
const services=[['01','Номнависии духтур','Духтур, беморхона, сана ва вақти мувофиқро онлайн интихоб кунед.','♥'],['02','Маълумотномаи судӣ','Барои гирифтани маълумотномаи судӣ дархост пешниҳод кунед.','✓'],['03','ИНН онлайн','Рақами мушаххаси андозсупорандаро дархост ё санҷед.','№'],['04','Шаҳодатномаи таваллуд','Маълумоти навзодро онлайн ирсол ва ҳуҷҷатҳоро бор кунед.','□']]
const places=[['01','Панҷакенти қадим','HERITAGE','https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1200&q=85'],['02','Саразм','UNESCO','https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1200&q=85'],['03','Ҳафт Кӯл','NATURE','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85']]
function Home(){return <><section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-grid"/><div className="hero-content reveal visible"><div className="eyebrow"><span/> ПАНҶАКЕНТ · ТОҶИКИСТОН</div><h1>МАҚОМОТИ ИҶРОИЯИ<br/><em>ҲОКИМИЯТИ МАҲАЛЛИИ<br/>ШАҲРИ ПАНҶАКЕНТ</em></h1><p>Шаҳри таърих ва оянда. Платформаи ягонаи рақамии Панҷакент барои хизматрасонӣ, хабарҳо, сайёҳӣ ва муроҷиати шаҳрвандон.</p><div className="hero-buttons"><Link to="/services" className="btn btn-primary">Хизматрасониҳо <span>→</span></Link><Link to="/tourism" className="btn btn-glass">Роҳнамои шаҳр <span>⌖</span></Link></div></div><div className="scroll-hint">SCROLL TO EXPLORE ↓</div></section><section className="section reveal"><SectionHeader number="01" label="NEWS BLOG" title="Блоги хабарҳо" link="Ҳама →"/><NewsGrid compact/></section><section className="section history-preview reveal"><SectionHeader number="02" label="HISTORY & CULTURE" title="Таърих ва фарҳанги Панҷакент" link="Кашф кардан →"/><div className="history-feature"><div><div className="eyebrow">SARAZM · PAGES FROM HISTORY</div><h3>Саразм — гаҳвораи тамаддуни Осиёи Марказӣ</h3><p>Дар канори Панҷакент яке аз қадимтарин марказҳои шаҳрнишинии минтақа ҷойгир аст. Саразм моро ба ҳазорсолаҳо пеш мебарад ва нишон медиҳад, ки мардум дар ин сарзамин чӣ гуна зиндагӣ, ҳунармандӣ ва тиҷорат мекарданд.</p><Link to="/history" className="btn btn-primary">Хондани мақола →</Link></div><img src="https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1200&q=85" alt="Мероси таърихии Панҷакент"/></div></section><section className="services-section"><div className="section reveal"><SectionHeader number="03" label="E-GOVERNMENT" title="Хизматрасониҳои давлатӣ"/><ServiceGrid/></div></section><section className="section reveal"><SectionHeader number="04" label="EXPLORE" title="Роҳнамои туристии Панҷакент"/><PlacesGrid/></section><DigitalSection compact/><section className="section reveal"><Appeal/></section></>}
function NewsPage(){return <PageHero label="NEWS BLOG" title="Блоги хабарҳо" intro="Ахбор, фарҳанг, чорабиниҳо ва эълонҳои муҳими Панҷакент дар як ҷо."><NewsGrid/></PageHero>}
function HistoryPage(){return <PageHero label="HISTORY & CULTURE" title="Таърих ва фарҳанги Панҷакент" intro="Аз Саразми бостонӣ то мероси шаҳрии Панҷакенти қадим — саҳифаҳои таърихи шаҳрро кашф кунед."><article className="history-article"><img className="history-cover" src="https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1600&q=90" alt="Саразм ва мероси бостонӣ"/><div className="history-copy"><small>ТАЪРИХ ВА ФАРҲАНГ · 29 АВГУСТ 2026</small><h2>Саразм — гаҳвораи тамаддуни Осиёи Марказӣ</h2><p>Дар водии Зарафшон, дар наздикии Панҷакент, осори Саразм моро ба даврае мебарад, ки ҳазорон сол пеш ҷомеаҳои муқимӣ шакл мегирифтанд. Ин маҳал танҳо як ёдгории қадимӣ нест — он равзанаест ба зиндагии мардум, ҳунармандӣ ва робитаҳои тиҷоратии ҷаҳони қадим.</p><h3>Саразм аз куҷо оғоз мешавад?</h3><p>Саразм ҳамчун маркази қадимаи маскунӣ ва ҳунармандӣ аҳамияти бузург дорад. Бозёфтҳои бостоншиносӣ аз рушди кишоварзӣ, коркарди металл, кулолгарӣ ва мубодилаи молҳо шаҳодат медиҳанд. Маҳз чунин робитаҳо водии Зарафшонро ба як нуқтаи муҳими робитаҳои фарҳангӣ табдил дода буданд.</p><h3>Панҷакенти қадим — шаҳри пурҷӯшу хурӯш</h3><p>Панҷакенти қадим яке аз муҳимтарин марказҳои фарҳангии Суғди бостон буд. Харобаҳои шаҳр, кӯчаҳо, хонаҳо ва осори санъат тасаввур медиҳанд, ки дар ин ҷо ҳаёти шаҳрӣ бо ҳунармандӣ, савдо ва фарҳанги ғанӣ пайваст буд.</p><h3>Меросе барои имрӯз</h3><p>Имрӯз таърихи Панҷакент қисми ҷудонашавандаи ҳувияти шаҳр ва ҷозибаи он барои сайёҳон аст. Шиносоӣ бо ин мерос ба мо кӯмак мекунад, ки гузашта ва рушди имрӯзаи шаҳрро беҳтар дарк кунем.</p><div className="history-cta"><b>Панҷакентро аз наздик бинед.</b><span>Ба Саразм ва Панҷакенти қадим сафар кунед ва таассуроти худро дар шарҳҳо бо мо мубодила намоед.</span><Link to="/tourism" className="btn btn-primary">Нақшаи сафар →</Link></div></div></article></PageHero>}
function ServicesPage(){return <PageHero label="E-GOVERNMENT" title="Хизматрасониҳои давлатӣ" intro="Хизматрасониҳои рақамиро зуд, шаффоф ва қулай истифода баред."><InteractiveServicesPage/></PageHero>}
function TourismPage(){return <PageHero label="DISCOVER" title="Роҳнамои туристии Панҷакент" intro="Панҷакенти қадим, Саразм ва Ҳафт Кӯлро кашф кунед."><PlacesGrid/><div className="tourism-info"><div><b>Масири тавсияшуда</b><span>Панҷакенти қадим → Саразм → Ҳафт Кӯл</span></div><div><b>Ёрии фаврӣ</b><span>112 · Хадамоти наҷот · беморхона</span></div></div></PageHero>}
function DigitalPage(){return <PageHero label="DIGITAL PANJAKENT" title="Панҷакенти рақамӣ" intro="Нишондиҳандаҳо, рушди инфрасохтор ва ташаббусҳои smart city."><DigitalSection/></PageHero>}
function AppealsPage(){return <PageHero label="CIVIC ENGAGEMENT" title="Муроҷиати шаҳрвандон" intro="Масъалаҳоро хабар диҳед, пешниҳод фиристед ва ҳолати муроҷиатро пайгирӣ кунед."><Appeal/><div className="issue-board"><IssueCard title="Роҳи маҳалла таъмирталаб аст" status="Нав"/><IssueCard title="Равшании кӯча барқарор шуд" status="Ҳалшуда"/><IssueCard title="Ҷамъоварии партовҳо" status="Дар раванд"/></div></PageHero>}
function PageHero({label,title,intro,children}:{label:string;title:string;intro:string;children:React.ReactNode}){return <section className="page-shell"><div className="section page-inner reveal visible"><div className="page-hero"><div className="eyebrow"><span/> {label}</div><h1>{title}</h1><p>{intro}</p></div>{children}</div></section>}
function NewsGrid({compact=false}:{compact?:boolean}){return <div className={`news-grid ${compact?'compact':''}`}>{news.map((item,i)=><article className={`news-card ${i===0?'featured':''}`} key={item.title}><div className="card-image"><img src={item.image} alt=""/><span>{item.tag}</span></div><div className="card-body"><small>29 АВГУСТ 2026</small><h3>{item.title}</h3><p>{item.text}</p><Link to="/news">Хондан <span>↗</span></Link></div></article>)}</div>}
function ServiceGrid(){return <div className="service-grid">{services.map(([n,title,text,icon])=><article className="service-card" key={title}><div className="service-top"><span className="number">{n}</span><span className="service-icon">{icon}</span></div><h3>{title}</h3><p>{text}</p><Link to="/services">Оғоз кардан <span>→</span></Link></article>)}</div>}
function PlacesGrid(){return <div className="places-grid">{places.map(([n,title,tag,image])=><article className="place-card" key={title}><img src={image} alt={title}/><div className="place-overlay"/><div className="place-top"><span>{n}</span><span>{tag}</span></div><div className="place-bottom"><h3>{title}</h3><button>Кашф кардан →</button></div></article>)}</div>}
function DigitalSection({compact=false}:{compact?:boolean}){return <section className={`digital ${compact?'digital-compact':''}`}><div className="section digital-inner reveal visible"><SectionHeader number="05" label="DIGITAL PANJAKENT" title="Панҷакенти рақамӣ" light/><p className="digital-lead">Технология, инфрасохтор ва ташаббусҳои smart city барои рушди устувори шаҳр.</p><div className="metrics"><Metric value="+12%" label="Growth"/><Metric value="48" label="Schools"/><Metric value="87%" label="Digital"/><Metric value="126" label="Projects"/></div><div className="chart"><div><b>Индекси рушди рақамӣ</b><span>2015 — 2026 ↗</span></div><div className="bars">{[25,32,30,39,48,44,57,64,61,75,86,100].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div></div></section>}
function Appeal(){return <div className="appeal"><div><div className="eyebrow accent">06 / CIVIC ENGAGEMENT</div><h2>Шаҳри худро<br/><em>якҷоя беҳтар мекунем.</em></h2><p>Масъалаҳои маҳаллиро хабар диҳед, пешниҳод фиристед ва ҳолати муроҷиататонро онлайн пайгирӣ кунед.</p></div><div className="appeal-actions"><Link to="/appeals" className="btn btn-primary">Муроҷиат фиристед →</Link><Link to="/appeals" className="btn btn-outline">Дидани масъалаҳо</Link></div></div>}
function IssueCard({title,status}:{title:string;status:string}){return <article className="issue-card"><span>{status}</span><b>{title}</b><small>Панҷакент · имрӯз</small></article>}
function SectionHeader({number,label,title,link,light=false}:{number:string;label:string;title:string;link?:string;light?:boolean}){return <div className={`section-head ${light?'light':''}`}><div><div className="eyebrow"><span/> {number} · {label}</div><h2>{title}</h2></div>{link&&<Link to={link.includes('Кашф')?'/history':'/news'} className="all-link">{link}</Link>}</div>}
function Metric({value,label}:{value:string;label:string}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/news" element={<NewsPage/>}/><Route path="/history" element={<HistoryPage/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/tourism" element={<TourismPage/>}/><Route path="/digital" element={<DigitalPage/>}/><Route path="/appeals" element={<AppealsPage/>}/><Route path="*" element={<Home/>}/></Routes>}
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><Layout><App/></Layout></BrowserRouter></StrictMode>)
